# Generated by Django 5.2.7 on 2025-11-09 02:56

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('ordered', 'Đã Đặt Hàng'), ('preorder', 'Đặt Trước'), ('delivered', 'Đã Giao Hàng'), ('canceled', 'Đã Hủy'), ('returned', 'Đã Trả Hàng'), ('done', 'Hoàn Thành')], default='Đã Đặt Hàng', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=10, max_length=20, prefix='cat_', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=10, max_length=20, prefix='pro_', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Bản Nháp'), ('disabled', 'Vô Hiệu Hóa'), ('availible', 'Có Sẵn')], default='Đang xem xét', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=8, max_length=20, prefix='sku_', unique=True),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='core.product'),
        ),
    ]
