# Generated by Django 5.2.7 on 2025-11-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_url', models.TextField(blank=True, null=True)),
                ('banking_code', models.CharField(default='970436', max_length=20)),
                ('account_number', models.CharField(default='1028841469', max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Payment Transactions',
            },
        ),
    ]
