# Generated by Django 5.2.7 on 2025-11-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymenttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
