# Generated by Django 5.2.7 on 2025-12-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
