# Generated by Django 5.2.7 on 2025-12-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
