# Generated by Django 5.2.7 on 2025-12-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cartorder_district_name_cartorder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='address_line',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
