# Generated by Django 5.2.7 on 2025-12-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartorder_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Chatbot',
            },
        ),
    ]
