# Generated by Django 5.2.7 on 2025-12-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Bản Nháp'), ('disabled', 'Vô Hiệu Hóa'), ('availible', 'Có Sẵn')], default='disabled', max_length=20),
        ),
    ]
