# Generated by Django 5.2.7 on 2025-12-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_product_status_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Bản Nháp'), ('disabled', 'Vô Hiệu Hóa'), ('available', 'Có Hàng')], default='disabled', max_length=20),
        ),
    ]
