# Generated by Django 6.0 on 2025-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_chatbotfaq_options_chatbotlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
