# Generated by Django 6.0 on 2025-12-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='get_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
