# Generated by Django 5.2.9 on 2025-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_get_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='get_percentage',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('ordered', 'Đã Đặt Hàng'), ('canceled', 'Đã Hủy'), ('returned', 'Đã Trả Hàng'), ('done', 'Hoàn Thành')], default='Đã Đặt Hàng', max_length=20),
        ),
    ]
