# Generated by Django 5.2.9 on 2025-12-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_product_get_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='points_required',
            field=models.IntegerField(default=0),
        ),
    ]
